global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'veo-scraper'
    static_configs:
      - targets: ['web:5000']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'celery'
    static_configs:
      - targets: ['worker:5555']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']